WeddingPlanner2/Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeddingPlanner2.Models
{
    [Table("weddings")]
    public class Wedding
    {
        [Key]
        public int WeddingID {get;set;}
        public int OrganizerID {get;set;}
        public string Bride {get;set;}
        public string Groom {get;set;}
        public DateTime Date {get;set;}
        public string Address {get;set;}
        public DateTime CreatedAt{get;set;} = DateTime.Now;
        public DateTime UpdatedAt {get;set;} = DateTime.Now;
        public User Organizer {get;set;}
        public List<Guest> Guests {get;set;}
    }

}

WeddingPlanner2/Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace WeddingPlanner2.Controllers
{
    [Route("weddings")]
    public class WeddingController : Controller
    {
        private int? UserSession
        {
            get { return HttpContext.Session.GetInt32("UserId"); }
            set { HttpContext.Session.SetInt32("UserId", (int)value); }
        }
        private MyContext dbContext;
        public WeddingController(MyContext context)
        {
            dbContext = context;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            List<Wedding> allWeddings = dbContext.Weddings
                                            .Include(w => w.Guests).ToList();
            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            ViewBag.UserSession = UserSession;
            return View(allWeddings);
        }

        [HttpGet("new")]
        public IActionResult New()
        {
            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            ViewBag.FirstName = HttpContext.Session.GetString("FirstName");
            ViewBag.UserSession = UserSession;
            return View();
        }

        [HttpPost("create")]
        public IActionResult Create(Wedding newWedding)
        {
            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            if(ModelState.IsValid)
            {
                newWedding.OrganizerID = (int)UserSession;
                dbContext.Weddings.Add(newWedding);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("New");
        }

        [HttpGet("{weddingID}")]
        public IActionResult Show(int weddingID)
        {
            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            Wedding thisWedding = dbContext.Weddings
                .Include(w => w.Guests)
                .ThenInclude(g => g.User)
                .Where(w => w.WeddingID == weddingID)
                .FirstOrDefault();
            
            ViewBag.UserSession = UserSession;
            return View(thisWedding);
        }

        [HttpGet("rsvp/{weddingID}")]
        public IActionResult RSVP(int weddingID)
        {

            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            Guest newGuest = new Guest()
            {
                WeddingID = weddingID,
                UserID = (int)UserSession
            };

            dbContext.Guests.Add(newGuest);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet("unrsvp/{weddingID}")]
        public IActionResult UNRSVP(int weddingID)
        {

            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            Guest goodbyeGuest = dbContext.Guests.FirstOrDefault(g => g.WeddingID == weddingID && g.UserID == UserSession);

            if(goodbyeGuest == null)
                return RedirectToAction("Index");

            dbContext.Guests.Remove(goodbyeGuest);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet("delete/{weddingID}")]
        public IActionResult Delete(int weddingID)
        {
            if(UserSession == null)
                return RedirectToAction("Index", "Home");

            Wedding goodbyeWedding = dbContext.Weddings.FirstOrDefault(w => w.WeddingID == weddingID);

            dbContext.Weddings.Remove(goodbyeWedding);
            dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WeddingPlanner2/Views/Wedding/Index.cshtml
@using WeddingPlanner2.Models
@model List<Wedding>



<div class="row">
    <h4 class="display-4">Welcome to the Wedding Planner, @ViewBag.FirstName</h4>
</div>

<table class="table table-striped">
    <thead>
        <th>Wedding</th>
        <th>Date</th>
        <th>Guests</th>
        <th>Actions</th>
    </thead>
    <tbody>
        @foreach(var wedding in Model)
        {
        <tr>
            <td><a asp-controller="Wedding" asp-route-weddingID="@wedding.WeddingID" asp-action="Show">@wedding.Bride & @wedding.Groom</a></td>
            <td>@wedding.Date</td>
            <td>@wedding.Guests.Count</td>
            <td>
                @if(ViewBag.UserSession == @wedding.OrganizerID)
                {
                    <a asp-action="Delete" asp-controller="Wedding" asp-route-weddingID="@wedding.WeddingID">Delete</a>
                }
                else
                {
                    if(@wedding.Guests.Any(g => g.UserID == ViewBag.UserSession))
                    {
                        <a asp-action="UNRSVP" asp-controller="Wedding" asp-route-weddingID="@wedding.WeddingID">UN-RSVP</a>
                    }
                    else
                    {
                        <a asp-action="RSVP" asp-controller="Wedding" asp-route-weddingID="@wedding.WeddingID">RSVP</a>
                    }

                }
            </td>
        </tr>
        }
    </tbody>
</table>

<div class="text-right">
    <a href="/weddings/new" class="btn btn-outline-dark">New Wedding</a>
</div>

WeddingPlanner2/Views/Wedding/New.cshtml
@using WeddingPlanner2.Models
@model Wedding

<h4 class="display-4 mb-5 text-center">Plan Your Wedding</h4>

<div class="offset-3 col-6">
    <form asp-action="create" asp-controller="Wedding" method="POST">
        <div class="form-group">
            <label asp-for="Bride"></label>
            <input asp-for="Bride" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Groom"></label>
            <input asp-for="Groom" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Date"></label>
            <input asp-for="Date" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control">
        </div>
        <div class="text-right">
            <button type="submit" class="btn btn-outline-dark">Add Wedding</button>
        </div>
    </form>
</div>

WeddingPlanner2/Views/Wedding/Show.cshtml
@using WeddingPlanner2.Models
@model Wedding


<h4 class="display-4">@Model.Bride & @Model.Groom 's Wedding</h4>
<div class="row">
    <div class="col">
        <div class="pl-5">
            <p>Date: @Model.Date</p>
            <p>Guest List</p>
            <div class="pl-5">
                @foreach(var guest in Model.Guests)
                {
                    <p>@guest.User.FirstName @guest.User.FirstName</p>
                }
            </div>
        </div>
    </div>
    <div class="col">
        <img src="https://maps.googleapis.com/maps/api/staticmap?center=@Model.Address&zoom=13&size=480x480&markers=@Model.Address&key=AIzaSyBxkD8afHOPA6xBHwFSaOZk54ePi6V9OYM" alt="Google Map of @Model.Address">
    </div>
</div>